# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_visit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateField(null=True),
        ),
    ]
